server:
  # 端口号
  port: 8080

spring:
  profiles:
    active: mysql
  jackson:
    # 设置后台返参，若字段值为 null, 是否返回
#    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      # 限制上传文件大小
      max-file-size: 10MB
  data:
    mongodb:
      uri: mongodb://blog:blog123456@192.168.31.177:27017/blog
      authentication-database: blog

mongo-plus:
  data:
    mongodb:
      database: blog
      connectTimeoutMS: 50000
      host: 192.168.31.177
      port: 27017
      username: blog
      password: blog123456
      authentication-database: blog

jwt:
  # 签发人
  issuer: lsm1998
  # 秘钥
  secret: gR6cytlUlgMfVh08nLFZf8hMk4mdJDX5rWBVlsCbKvRlWcLwNRU6+rIPcLx21x191kJgP8udtoZuHt5yUDWtgg==
  # token 过期时间（单位：分钟） 24*60
  tokenExpireTime: 1440
  # token Header 中的 key 值
  tokenHeaderKey: Authorization
  # token Header 中的 value 值前缀
  tokenPrefix: Bearer

  
#=================================================================
# minio (上传图片需要，需配置成自己的地址)
#=================================================================
minio:
  endpoint: http://192.168.31.199:9500
  accessKey: J0eiyn2XdBpLG0Wmi0oV
  secretKey: MnLEGUBgLhSQ1p591Xn76o2IF5THC3Ki8AvmflA5
  bucketName: blog
  accessUrl: https://cdn.lsm1998.com

#=================================================================
# IP归属地信息库文件路径 ip2region.xdb
#=================================================================
xdb:
  profile: ip2region.xdb
