build:
    docker build -t weblog-web:v1 .

tag:
    docker tag  weblog-web:v1 ccr.ccs.tencentyun.com/lsm1998/weblog-web:v1
    docker push ccr.ccs.tencentyun.com/lsm1998/weblog-web:v1



# 优秀的前端后台管理系统
# https://github.com/arco-design/arco-design-pro-vue
# https://github.com/pure-admin/vue-pure-admin
# https://github.com/Tencent/tdesign-vue-next-starter